export const ApiRoutes = {
  branchList: 'branch/all',
  branchCreate: 'branch/',
  branchFilter: 'branch/filter',
  counterList: 'counter',
  counterCreate: 'counter',
  counterUpdate: 'counter',
  counterDelete: 'counter',
  userLogin: 'user/login',
  currencyList: 'currency',
  userRegister: 'register',
  userList: 'user/all',
  transferStatus: 'transfertstatus',
  transferTypeList: 'transfertType',
  ticketClose: '/ticket/close',
  ticketCreate: 'ticket',
  ticketList: 'ticket/all',
  ticketEdit: 'ticket/edit',
  ticketCall: 'ticket/call',
  ticketFilter: 'ticket/filter',
}
